
import React, { useState } from 'react';
import { Sparkles, Book, Send, Loader2 } from 'lucide-react';
import { generateDevotional } from '../services/gemini';

const AICompanion: React.FC = () => {
  const [topic, setTopic] = useState('');
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topic.trim()) return;

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const generatedText = await generateDevotional(topic);
      setResult(generatedText);
    } catch (err) {
      setError("Sorry, our devotional assistant is currently unavailable. Please check your connection or API key.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="py-20 bg-gradient-to-br from-church-50 to-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div className="text-center mb-10">
          <div className="inline-flex items-center justify-center p-3 bg-indigo-100 rounded-full mb-4">
             <Sparkles className="w-6 h-6 text-indigo-600" />
          </div>
          <h2 className="text-3xl md:text-4xl font-serif font-bold text-church-900 mb-4">Scripture Companion</h2>
          <p className="text-slate-600 max-w-2xl mx-auto">
            Need encouragement? Enter a word (e.g., "Hope", "Anxiety", "Family") or a question, and let our AI assistant generate a short devotional and prayer based on biblical wisdom for the Utsaha Jagrity Mandali family.
          </p>
        </div>

        <div className="bg-white rounded-2xl shadow-xl p-6 md:p-10 border border-slate-100">
          <form onSubmit={handleGenerate} className="flex flex-col md:flex-row gap-4 mb-8">
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="What do you need prayer or wisdom for today?"
              className="flex-1 px-5 py-4 rounded-xl border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 outline-none text-lg transition-all"
            />
            <button
              type="submit"
              disabled={loading || !topic.trim()}
              className="bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-300 text-white font-semibold px-8 py-4 rounded-xl flex items-center justify-center transition-colors min-w-[160px]"
            >
              {loading ? <Loader2 className="animate-spin h-5 w-5" /> : <><Send className="w-5 h-5 mr-2" /> Inspire Me</>}
            </button>
          </form>

          {error && (
            <div className="bg-red-50 text-red-700 p-4 rounded-lg border border-red-100 mb-6">
              {error}
            </div>
          )}

          {result && (
            <div className="bg-church-50 rounded-xl p-6 md:p-8 animate-fade-in">
              <div className="flex items-start gap-4">
                <Book className="w-8 h-8 text-church-600 flex-shrink-0 mt-1" />
                <div className="prose prose-lg text-slate-700 max-w-none">
                  <div className="whitespace-pre-wrap leading-relaxed">
                    {result}
                  </div>
                </div>
              </div>
              <div className="mt-6 pt-6 border-t border-church-200 flex justify-end">
                <p className="text-xs text-slate-400 italic">Generated by AI • Verify with Scripture</p>
              </div>
            </div>
          )}

          {!result && !loading && !error && (
            <div className="text-center py-10">
               <div className="inline-block px-4 py-2 bg-slate-50 rounded-lg text-sm text-slate-400">
                  Try topics like: "Strength", "Grace", "Faithfulness"
               </div>
            </div>
          )}
        </div>

      </div>
    </div>
  );
};

export default AICompanion;
